__author__ = 'ryansollars'
# #Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


x = 1
y = 0
z = 0
i = 0

while z <= 4000000:
    z = x + y
    y = x
    x = z

    if z % 2 == 0:
        i += z
        print i


    # 2 = 0 + 1
    # 3 = 2 + 1
    # 5 = 3 + 2
    # 8 = 5 + 3